# находит email преподавателя по заданным ФИО

PREFIX : <http://misis.roz37.ru/semantic/schema/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT *
WHERE {
  GRAPH <http://misis.roz37.ru//cv/mishurov>
  {
    ?строкаДанных ?p2 ?признакиСтрокиДанных;
                  rdf:type "http://misis.roz37.ru/semantic/онтология/Преподаватели". #выбираем строки с преподавателями
    ?признакиСтрокиДанных :label "ФИО" ; :значение "Хоботов Лев Евгеньевич". #условие для выбора нужной строки поле ФИО содержит "Хоботов ..."
    ?строкаДанных ?p3 ?всеПризнакиНужнойСтрокиДанных.
    ?всеПризнакиНужнойСтрокиДанных :label "Рабочая эл. почта"; :значение ?email #выбираем признак email
  }
}
