
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX онтология: <https://lipers24.ru/semantic/онтология/>
PREFIX свойства: <https://lipers24.ru/semantic/schema/>

# формирует реестр предметов из автоматически сегенерированного RDF

SELECT DISTINCT ?предметнаяОбласть ?названиеПредмета ?кодПредмета
WHERE {
  GRAPH <http://lipers24.ru/УП/ООО/OOO-UP-2018-2.xlsx>
  {
    ?предмет rdf:type онтология:Предмет;
    		 свойства:названиеПредмета ?названиеПредмета;
             свойства:кодПредмета ?кодПредмета
 	OPTIONAL{?предмет свойства:предметнаяОбласть ?предметнаяОбласть}
  }
}
