PREFIX example: <http://example.com/semantic/schema/>

SELECT DISTINCT ?предметнаяОбласть ?названиеПредмета ?кодПредмета
WHERE {
  GRAPH <http://lipers24.ru/УП/ООО/OOO-UP-2018-1.xlsx>
  {
    ?реестр example:строка [
        example:свойство-1 [example:значение ?предметнаяОбласть];
        example:свойство-2 [example:значение ?названиеПредмета];
        example:свойство-3 [example:значение ?кодПредмета]
    ]          
  }
}