PREFIX example: <http://example.com/semantic/schema/>

# извлекает список предметов
 
SELECT DISTINCT ?названиеПредмета ?кодПредмета
WHERE {
  GRAPH <http://lipers24.ru/УП/ООО/OOO-UP-2018-1.xlsx>
  {
    ?реестр example:строка [
        example:свойство-2 [example:значение ?названиеПредмета];
        example:свойство-3 [example:значение ?кодПредмета];
                            
    ]
  }
}