# находит публикации квартилей Q1 и Q2 преподавателей, которые защитили диссертацию докторскую после в 2005 года 

PREFIX xs: <http://www.w3.org/2001/XMLSchema#>
PREFIX свойство: <http://misis.roz37.ru/semantic/schema/>
PREFIX класс: <http://misis.roz37.ru/semantic/онтология/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?g ?фамилия ?имя ?индекс ?квартиль ?публикация
WHERE {
  GRAPH ?g
  {
    ?анкетныеДанные rdf:type класс:Преподаватели. 
    ?анкетныеДанные свойство:ученаяСтепень [свойство:label ?ученаяСтепень; свойство:год ?годПрисуждения];
                    свойство:фамилия ?фамилия; свойство:имя ?имя.
    ?научныеПубликации свойство:квартильВИндексеЦитирований ?квартиль;
                       свойство:наличиеВИндексеЦитирований ?индекс;
                       свойство:библиографическаяЗапись ?публикация
  }
  FILTER (xs:integer(?годПрисуждения) >= 2005)
  FILTER STRSTARTS(?ученаяСтепень, "д")
  FILTER REGEX (?квартиль, "^Q[1|2]{1}")
}