# находит публикации квартилей Q1 и Q2 преподавателей, которые защитили докторскую диссертацию  после в 2005 года

PREFIX xs: <http://www.w3.org/2001/XMLSchema#>
PREFIX схема: <http://misis.roz37.ru/semantic/schema/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?фамилия ?имя ?индекс ?квартиль ?публикация
WHERE {
  GRAPH ?g
  {
    ?анкетныеДанные rdf:type "http://misis.roz37.ru/semantic/онтология/Преподаватели". 
    ?анкетныеДанные схема:ученаяСтепень [схема:label ?ученаяСтепень; схема:год ?годПрисуждения];
                    схема:фамилия ?фамилия; схема:имя ?имя.
    ?научныеПубликации схема:квартильВИндексеЦитирований ?квартиль;
                       схема:наличиеВИндексеЦитирований ?индекс;
                       схема:библиографическаяЗапись ?публикация
  }
  FILTER (xs:integer(?годПрисуждения) >= 2005)
  FILTER STRSTARTS(?ученаяСтепень, "д")
  FILTER REGEX (?квартиль, "^Q[1|2]{1}")
}