# находит URI преподавателя по ФИО в наборе данных "РеестрППС" 
# и возвращает его email из набора данных "Анкеты"

PREFIX свойство: <http://misis.roz37.ru/semantic/schema/>
PREFIX класс: <http://misis.roz37.ru/semantic/онтология/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?email
WHERE {
  GRAPH ?g1
  {
    ?s1 rdf:type класс:РеестрППС.
    ?преподаватель rdf:type класс:Преподаватели;
                   свойство:фамилия "Мишуров";
                   свойство:имя "Сергей";
                   свойство:отчество "Сергеевич"
  }
  GRAPH ?g2
  {
    ?s2 rdf:type класс:Анкеты.
    ?преподаватель свойство:email ?email
  }
}