# находит email преподавателей, которые защитили диссертацию после в 2005 года

PREFIX схема: <http://misis.roz37.ru/semantic/schema/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?email
WHERE {
  GRAPH <http://misis.roz37.ru/cv/hobotov-2>
  {
    ?строкаДанных ?p2 ?признакиСтрокиДанных;
                  rdf:type "http://misis.roz37.ru/semantic/онтология/Преподаватели". 
    ?строкаДанных схема:ученаяСтепень [схема:label ?ученаяСтепень; схема:год ?годПрисуждения];
                  схема:email ?email
  }
  FILTER (?годПрисуждения >= "2005")
}