# находит email преподавателя по заданным ФИО

PREFIX схема: <http://misis.roz37.ru/semantic/schema/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?email
WHERE {
  GRAPH <http://misis.roz37.ru/cv/hobotov-auto>
  {
    ?строкаДанных ?p2 ?признакиСтрокиДанных;
                  ?p3 ?всеПризнакиНужнойСтрокиДанных;
                  rdf:type "http://misis.roz37.ru/semantic/онтология/Преподаватели". #выбираем строки с преподавателями
    ?признакиСтрокиДанных схема:label "ФИО" ; схема:значение "Хоботов Лев Евгеньевич". #выбираем строки, в которых ФИО содержит "Мишуров..."
    ?всеПризнакиНужнойСтрокиДанных схема:label "Рабочая эл. почта"; схема:значение ?email #выбираем признак email
  }
}