PREFIX : <http://misis.roz37.ru/semantic/schema/>
PREFIX класс: <http://misis.roz37.ru/semantic/онтология/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# публикации Q1 и Q2

SELECT (CONCAT(?фамилия, " ", ?имя, " ", ?отчество) AS ?ФИО) ?годПубликации ?индекс ?квартиль ?библиографическаяЗапись
WHERE {
  GRAPH ?преподаватели
  {
    ?преподаватель rdf:type класс:Преподаватели; # выводим ФИО найденных преподавателей
                   :фамилия ?фамилия;
                   :имя ?имя;
                   :отчество ?отчество;
                   :хешАнкетыПреподавателя ?хеш # анкета преподавателя верифицирована администратором
  }
  GRAPH ?анкеты
  {
    ?преподаватель :научнаяПубликация 
        [ 
            :наличиеВИндексеЦитирований ?индекс; 
            :квартильВИндексеЦитирований ?квартиль; 
            :годПубликации ?годПубликации ; 
            :библиографическаяЗапись ?библиографическаяЗапись
        ]
  }
  FILTER (REGEX(?квартиль, "^Q[1|2]{1}"))
}
ORDER BY ?ФИО