# находит URI преподавателя по ФИО в наборе данных "РеестрППС" 
# и ищет его email в пределах всей базы

PREFIX свойство: <http://misis.roz37.ru/semantic/schema/>
PREFIX класс: <http://misis.roz37.ru/semantic/онтология/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?email 
WHERE {
  GRAPH ?g1
  {
    ?преподаватель rdf:type класс:Преподаватели; # находим идентификатор нужного преподавателя
                   свойство:фамилия "Мишуров";
                   свойство:имя "Сергей";
                   свойство:отчество "Сергеевич"
  }
  GRAPH ?g2
  {
    ?преподаватель свойство:email ?email # ищем его email по всей базе
  }
}